name = "qr-code-generator"
account_id = "ed96d4cf5dacddf0033a768d878b6cbc"
main = "./dist/_worker.js/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

workers_dev = true

[assets]
directory = "./dist"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "qr_generator_db"
database_id = "8b44bfa0-2c12-47ed-87b4-015d55a9b30b"

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "qr-assets"

[vars]
ENVIRONMENT = "production"
JWT_SECRET = "production-secret-min-32-chars-long-qr-super-key"
APP_URL = "https://freeqrcode-generator.com"
