import type { Locale } from '../../config';
import type { GuideArticleData } from './types';

const enData: GuideArticleData = {
  title: 'UPI QR Code for Shop: Free Setup Guide for Merchants',
  description:
    'Make a free UPI QR code for your shop — what goes inside the code, how to add a fixed amount, and 2026 UPI charges for merchants explained.',
  badge: 'Merchant Guide',
  h1: 'How to Make a UPI QR Code for Your Shop',
  subheadline:
    'A UPI QR code turns your counter into a digital payment terminal for zero upfront cost. This guide shows you exactly what goes inside the code, how to build one free in minutes, when to fix an amount, what the new 2026 UPI charges mean for you, and the sticker-swap scam every merchant must know about.',
  readingTime: '8 min read',
  updatedDate: 'October 2026',
  quickTakeawaysTitle: 'Quick Takeaways',
  quickTakeaways: [
    {
      label: 'It is just a text link',
      text: 'A UPI QR code encodes a upi://pay string with your UPI ID (pa), shop name (pn), and optionally a fixed amount (am) — no registration is required to generate one yourself.',
    },
    {
      label: 'Free to set up',
      text: 'Stick your own QR on a laminated card at the counter and customers can pay you in seconds — money lands in your bank account, usually within seconds.',
    },
    {
      label: 'Watch the new MDR rules',
      text: 'NPCI announced that from 15 October 2026, UPI merchant payments above ₹2,000 would attract a 0.4% MDR (capped at ₹300) — but as of October 2026 a deferral to January 2027 is reportedly under consideration, so check the latest status; small merchants under ₹1 lakh/month through QR keep zero MDR either way.',
    },
    {
      label: 'Tampering is the #1 risk',
      text: 'Check that your QR stickers have not been swapped or pasted over, and always confirm payment in your own UPI app — never trust the customer\'s screenshot.',
    },
  ],
  tocTitle: 'In This Guide',
  sections: [
    {
      id: 'what-is-upi-qr-code',
      heading: 'What Is a UPI QR Code for a Shop?',
      paragraphs: [
        'A UPI QR code is not a picture of your bank account or a token generated by a bank — it is simply a QR code that stores a short piece of text in a standard format that every UPI app (Google Pay, PhonePe, Paytm, BHIM) understands. When a customer scans it, their phone reads that text, extracts your UPI ID and shop name, and opens a ready-made payment screen addressed to you.',
        'The text follows the format upi://pay?pa=<your-upi-id>&pn=<your-shop-name>&am=<amount>&cu=INR&tn=<note>. The two fields that matter most are pa (your UPI ID, also called your VPA) and pn (your payee name). The amount (am) is optional: leave it out and the customer types the bill total themselves; include it and the payment screen opens with the exact amount pre-filled.',
        'This simplicity is what makes UPI QR codes so powerful for shops, street vendors, salons, clinics, and small businesses. There is no payment terminal to buy, no rental fee, and no hardware to maintain. The code itself is a static piece of text — it costs nothing to print, never needs a battery, and works even when the shop\'s internet is down (the customer\'s phone needs connectivity, but the QR sticker itself is offline).',
      ],
      callout: {
        title: 'Honest disclosure',
        text: 'This guide shows how to build a basic static UPI QR code yourself. If you want official merchant features — a printed QR sticker, a payment soundbox, branded QRs, or settlement reports — register as a merchant with your payment app (PhonePe Business, GPay for Business, Paytm for Business). The self-made code works for receiving money, but it gives you none of the merchant tooling or customer support.',
        type: 'info',
      },
    },
    {
      id: 'make-upi-qr-code-free',
      heading: 'How to Make a UPI QR Code Free: Step by Step',
      paragraphs: [
        'Building your own UPI QR code takes about five minutes and nothing more than your phone or computer. Here is the exact process:',
      ],
      subsections: [
        {
          subheading: '1. Know your UPI ID and shop name',
          text: 'Open your UPI app and find your UPI ID — it looks like yourname@okhdfcbank, yourname@ybl, or yourname@paytm. Also decide on the display name customers will see, e.g. "Sharma General Store". The name shown at payment time must be your real registered name or business name.',
        },
        {
          subheading: '2. Write your UPI payment string',
          text: 'Compose the string: upi://pay?pa=yourname@okhdfcbank&pn=Sharma%20General%20Store&cu=INR. Replace spaces in the name with %20 (URL encoding). Leave out the amount parameter entirely if you want customers to enter the bill total themselves.',
        },
        {
          subheading: '3. Paste it into the QR generator as URL type',
          text: 'Open the free QR code generator, choose the URL / website QR type, and paste your full upi://pay string into the input field. The QR code appears instantly. Yes, it works for upi:// links exactly like https:// links — a QR code is just encoded text.',
        },
        {
          subheading: '4. Add your shop logo and download',
          text: 'Add your shop logo in the center so customers recognize your brand and do not scan a stranger\'s code by mistake — use a high error-correction level if you do. Download the code as a high-resolution PNG for printing.',
        },
      ],
      figures: [
        {
          src: '/guides/screenshots/qr-type-selector.png',
          alt: 'Selecting the URL QR code type in the free generator to encode a UPI payment link',
          caption: 'Step 3: select the URL / website QR type — paste your upi://pay string there.',
        },
        {
          src: '/guides/screenshots/generator-hero.png',
          alt: 'Pasting a upi://pay UPI payment string into the free QR code generator',
          caption: 'Paste the full upi://pay string with your UPI ID — the code generates instantly, no sign-up.',
        },
        {
          src: '/guides/screenshots/download-buttons.png',
          alt: 'Downloading the UPI QR code in high resolution PNG for print',
          caption: 'Download a high-resolution PNG — print it sharp for the counter, flyers, and tent cards.',
        },
      ],
    },
    {
      id: 'fixed-amount-or-open',
      heading: 'Fixed Amount or Open Amount? Static vs Dynamic QR',
      paragraphs: [
        'The biggest design decision for a merchant QR code is whether the amount is baked into the code or left open. An open-amount code (the pa and pn parameters only) is the classic counter sticker: it never changes, you print it once, and the customer types the bill amount each time. This works perfectly for shops, vendors, and stalls where every bill is different.',
        'A fixed-amount code includes the am parameter, e.g. upi://pay?pa=yourname@okhdfcbank&pn=Sharma%20General%20Store&am=299&cu=INR. The customer\'s app opens with ₹299 pre-filled — one less thing to go wrong. This suits fixed-price items: entry tickets, a ₹50 parking slip, a menu item of the day, or a QR printed on each invoice with that invoice\'s total. Print a different fixed-amount code per price point, or per bill, and payment mistakes drop sharply.',
        'There is also a third category you will hear about: dynamic QR codes. These are generated live by a point-of-sale system or payment gateway for each transaction, usually carry a reference URL or transaction ID, and expire after a few minutes. Big retailers use them because they reconcile automatically and cannot be photocopied. Small merchants do not need this — a static code with the amount left open, plus checking each payment in your own app, is the practical setup.',
      ],
      bullets: [
        'Counter sticker (bills vary): open amount — customer enters the total.',
        'Fixed-price items: embed am= with the price — fewer wrong-amount mistakes.',
        'Per-invoice codes: generate one fixed-amount QR per bill and print it on the receipt.',
        'Dynamic, expiring QRs: only needed with POS or payment-gateway integration.',
      ],
    },
    {
      id: 'upi-charges-merchants-2026',
      heading: 'UPI Charges for Merchants in 2026: What Changed',
      paragraphs: [
        'For years, UPI merchant payments carried no charge at all. That is changing. NPCI has announced a Merchant Discount Rate (MDR) framework for UPI person-to-merchant (P2M) payments originally scheduled to take effect from 15 October 2026 — but as of October 2026, following pushback from merchant associations, NPCI is reportedly considering deferring the rollout to 1 January 2027, with a final decision expected in the coming days. An expanded exemption for businesses with annual turnover up to ₹40 lakh is also reportedly under consideration. Either way, as a merchant with a QR code at your counter, you should know exactly where you stand.',
        'The core rule: UPI payments up to ₹2,000 remain completely free of MDR. Above ₹2,000, a 0.4% MDR applies, capped at ₹300 per transaction — so a ₹3,000 payment costs ₹12 and anything ₹75,000 or above costs exactly ₹300. Person-to-person transfers (friends, family) stay free regardless of amount, and customers never pay the MDR themselves.',
        'Crucially, small merchants are protected: shops and vendors receiving up to ₹1 lakh per month through UPI QR codes under the person-to-person-merchant (P2PM) category continue to enjoy zero MDR. For the vast majority of kirana shops, street vendors, and small outlets, daily UPI income will keep arriving free of charge — the government has stated roughly 96% of merchant UPI transactions will remain unaffected.',
      ],
      callout: {
        title: 'What this means for your shop',
        text: 'If your monthly QR collections stay under ₹1 lakh, nothing changes for you — zero MDR. Larger merchants should watch their per-transaction amounts: keeping typical transactions at or under ₹2,000 (the norm at small shops) keeps them MDR-free. The charge falls within the payment ecosystem, not on your customer.',
        type: 'tip',
      },
    },
    {
      id: 'qr-fraud-safety',
      heading: 'The #1 Risk: QR Sticker Swapping and How to Stop It',
      paragraphs: [
        'The most common UPI QR scam does not involve hacking your phone — it involves a cheap printout. A fraudster sticks their own QR code over yours at the counter, or swaps your sticker when the shop is busy. Customers scan it, see a plausible shop name, pay the fraudster, and show you a genuine payment-success screenshot. You lose the money and often do not notice for days.',
        'Defense is simple and physical. Mount your QR code on something permanent — a framed stand, a laminated tent card screwed or taped to the counter, an acrylic display — rather than a loose paper sticker that anyone can lift. If you use stickers, initial them or sign across the corner so a swap is visually obvious, and check them at the start of every day.',
        'Equally important: never accept a customer\'s payment screenshot as proof. Screenshots can be faked in seconds. Confirm every payment in your own UPI app\'s transaction history before handing over the goods — or get a UPI payment soundbox (the small speaker many vendors now use) that announces each credited payment aloud, which makes swap fraud useless because the fraudster\'s payments never trigger your speaker.',
      ],
      callout: {
        title: 'Also verify the payee name',
        text: 'When a customer scans your code, their app shows your registered payee name. Tell regular customers what that exact name is, so they notice if a swapped code shows a stranger\'s name. Your pn parameter should always match your real registered name or business name — this is also why your self-made code uses your genuine UPI ID.',
        type: 'warning',
      },
    },
    {
      id: 'print-placement-tips',
      heading: 'Print and Placement Tips That Get More Scans',
      paragraphs: [
        'A QR code is only useful if people can actually scan it. The golden sizing rule: the code should be at least one-tenth as wide as the distance it will be scanned from. A counter code scanned at arm\'s length (about 50 cm) should be at least 5 cm wide — print it larger than feels necessary; bigger codes scan faster and tolerate bad lighting.',
        'Always keep a clean white margin around the code — the "quiet zone". Phone cameras use that empty border to detect the code\'s edges, and a design that bleeds graphics right up to the code is the most common reason a printed QR fails to scan. Black on white gives the highest contrast; if you brand it with colors, keep the modules dark and the background light.',
        'Placement matters as much as print quality. Put the code where the customer stands with their phone already out — right next to the billing counter, at eye level or flat on the counter in a small stand, never behind glass where reflections break scanning. One code per till is the minimum; delivery packing and receipts can carry a smaller copy so customers ordering later can still find your payment details.',
        'Test before you commit. Print one copy, scan it with two different phones (an Android and an iPhone if possible), in the actual shop lighting, from the distance customers will stand at. Confirm the right payee name appears. Only then print the full batch — reprinting a hundred stickers because of a typo in the UPI ID is an expensive lesson.',
      ],
      bullets: [
        'Size: at least 1/10th of the scanning distance (5 cm+ for counter use).',
        'Quiet zone: keep a clean white border all around the code.',
        'High contrast: black on white scans fastest; avoid dark backgrounds.',
        'Test with two phones in real lighting before printing in bulk.',
      ],
    },
  ],
  faqsTitle: 'UPI QR Code FAQs for Merchants',
  faqs: [
    {
      question: 'Is making a UPI QR code for my shop free?',
      answer:
        'Yes. A basic static UPI QR code is just your UPI payment string (upi://pay?pa=...&pn=...) encoded as a QR code — you can generate and print it free in minutes. Money goes straight to your linked bank account. Merchant registration with a payment app adds extras like soundboxes and settlement reports, but it is not required to start accepting payments.',
    },
    {
      question: 'Will I be charged for UPI payments I receive?',
      answer:
        'Under the MDR framework announced for 15 October 2026 (a deferral to January 2027 was reportedly under consideration as of October 2026 — check the latest status), UPI payments up to ₹2,000 carry zero MDR, and small merchants receiving up to ₹1 lakh per month through QR codes under the P2PM category continue to pay nothing. Above ₹2,000, a 0.4% MDR applies (capped at ₹300) for larger merchants. Customers always pay free — the charge never falls on the payer.',
    },
    {
      question: 'How do I add a fixed amount to my UPI QR code?',
      answer:
        'Add the amount parameter to your payment string: upi://pay?pa=yourname@bank&pn=Your%20Shop&am=299&cu=INR. When scanned, the customer\'s app opens with ₹299 pre-filled. Use the decimal format (e.g. 299.00) for paise precision. Fixed-amount codes are ideal for fixed-price items, tickets, and QRs printed on individual invoices.',
    },
    {
      question: 'Where does the money go when someone pays my QR code?',
      answer:
        'Directly into the bank account linked to your UPI ID — usually within seconds, 24×7 including holidays. You can see each payment in your UPI app\'s transaction history under the transaction note (tn) if you included one. Always confirm receipt in your own app rather than trusting a customer\'s screenshot.',
    },
    {
      question: 'What is the QR sticker swap scam?',
      answer:
        'A fraudster pastes their own QR code over yours, so customers pay them instead of you. Protect yourself: use a fixed countertop display instead of loose stickers, sign or mark your QR visibly, check it daily, tell customers your exact payee name, and always verify payments in your own UPI app or with a payment soundbox.',
    },
    {
      question: 'Can I add my shop logo to my UPI QR code?',
      answer:
        'Yes — adding a logo in the center makes your code recognizable and helps customers avoid scanning a stranger\'s code. Use a high error-correction level when adding a logo, keep the logo to about 20% of the code\'s area, and always test-scan the final printed version with multiple phones before rolling it out.',
    },
  ],
  ctaTitle: 'Make Your Shop\'s UPI QR Code Now',
  ctaDesc:
    'Build your UPI QR code in minutes — paste your upi://pay link, add your shop logo, and download a print-ready code. Free, no sign-up.',
  ctaButtonText: 'Create Free QR Code',
  ctaButtonLink: '/',
  ctaSecondaryText: 'How QR Codes Work',
  ctaSecondaryLink: '/guides/what-is-a-qr-code',
};

export function getUpiQrCodeForMerchantsData(_locale: Locale): GuideArticleData {
  return enData;
}
